[book]
title = "LPLang Book"
authors = ["rsyyd"]
language = "en"
src = "src"
build-dir = "book"

[output.html]
default-theme = "ayu"
mathjax-support = true
copy-fonts = true
curly-quotes = true

[output.html.fold]
enable = true
level = 2